baseurl = "https://divan.io/"
languageCode = "en-us"
title = "divan's blog"
[params]
	github = "divan"
	stackoverflow = "2739942"
	contact = "mailto:ivan.daniluk@gmail.com"
    bio = "Gopher. Figure skating enthusiast."
	subtitle = "random thoughts on Go, software and sports"

