baseurl = "https://divan.io/"
languageCode = "en-us"
title = "divan's blog"
[params]
	github = "divan"
	contact = "mailto:ivan.daniluk@gmail.com"
    bio = "Gopher. Figure skating enthusiast."
	subtitle = "random thoughts on Go, software and sports"
	disqus = "divanblog"
	avatar = "/images/avatar.jpg"

[blackfriday]
  angledQuotes = false
  fractions = false
  extensions = ["laxHtmlBlocks"]
